# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'src.core.scanner', 
        'src.core.cache_manager',
        'src.core.history', 
        'src.core.file_ops', 
        'src.core.image_hash', 
        'src.core.preset_manager', 
        'src.core.file_lock_checker', 
        'src.core.empty_folder_finder',
        'src.ui.main_window',
        'src.ui.theme',
        'src.ui.empty_folder_dialog',
        'src.ui.components.results_tree',
        'src.ui.dialogs.preset_dialog',
        'src.ui.dialogs.exclude_patterns_dialog',
        'src.ui.dialogs.shortcut_settings_dialog',
        'src.utils.i18n',
        'imagehash', 
        'PIL', 
        'send2trash', 
        'psutil',
        'sqlite3'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Python Standard Library exclusions (unused)
        'tkinter', 'unittest', 'email', 'http', 'xml', 'pydoc', 'distutils',
        'setuptools', 'pkg_resources', 'bz2', 'lzma', 
        
        # PySide6 Unused Modules (Heavy ones)
        'PySide6.QtNetwork',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuickWidgets',
        'PySide6.QtSensors',
        'PySide6.QtSerialPort',
        'PySide6.QtTest',
        'PySide6.QtWebChannel',
        'PySide6.QtWebEngine',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebSockets',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.QtCharts',
        'PySide6.QtDataVisualization',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtSql',
        'PySide6.QtBluetooth',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtLocation',
        'PySide6.QtNfc',
        'PySide6.QtPositioning',
        'PySide6.QtPrintSupport',
        'PySide6.QtRemoteObjects',
        'PySide6.QtScxml',
        'PySide6.QtTextToSpeech',
        'PySide6.QtUiextras',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PyDuplicateFinderPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='resources/icon.ico', # Uncomment if icon exists
)
